### ISSUE TITLE
FID score of conditional sampling

### ISSUE THREAD

**Issue by chen-hao-chao** [yang-song/score_sde#15]
Hi,

Thanks a lot for your amazing work.
I'm recently reproducing your work for conditional sampling. I found that the FID scores of the images sampled using the conditional sampling (a VE score model with a wide resnet classifier) is far higher than 2.20. Is there any suggestion for tuning the hyper-parameters to improve the performance? Or can you provide the FID score for this experimental setting for reference? It seems that the paper only provides some visualization example for this experiment.

Thanks.

**Comment by yang-song** [comment]
You might want to tune the temperature of the classifier, and the signal-to-noise ratio of the PC sampler. If you want to achieve better FIDs, it might be easier to directly learn score-based models conditioned on class labels, instead of guiding the sampling process with a classifier. I didn't compute the FID scores for this experimental setting.
