### ISSUE TITLE
When calculating the exact likelihood, why you do not add uniform noise to the input image?

### ISSUE THREAD

**Issue by huanranchen** [yang-song/score_sde#24]
Hi~
According to the definition of bpd
![image](https://github.com/yang-song/score_sde/assets/28839782/9a203e66-6704-4e9f-bae1-9b6499aeb469)
We should calculate the likelihood of x+u to approximate the bpd.

However, in this code, it directly calculate the likelihood of x instead of x+u. I test some image, and it even give me negative bpd (which means the probability of generating such image is greater than 1). Is this wrong?

**Comment by daihuiao** [comment]
Hello, I am also learning the likelihood calculation in score sde. Although I did not understand the formula you attached above, I feel that there is something wrong with the code implementation in the project.

I noticed that in the original code, the prior log probability (`prior_logp`) is calculated using [this line](https://github.com/yang-song/score_sde_pytorch/blob/cb1f359f4aadf0ff9a5e122fe8fffc9451fd6e44/likelihood.py#L104). This formula calculates `prior_logp` based on the final output of the ODE solver (see line 101: `zp = solution.y[:, -1]`), which means the prior log probability is computed by inputting the final denoised image into a Gaussian distribution.

However, according to the formula in the paper, the final likelihood should be the likelihood of the Gaussian distribution plus an integral term. Am I misunderstanding something?

Any response would be greatly appreciated.

**Comment by huanranchen** [comment]
> zp = solution.y[:, -1]

Hi @daihuiao,

The integral term is indeed represented by `solution.y[:, -1]` in line 101. At line 98:

```python
init = np.concatenate([mutils.to_flattened_numpy(data), np.zeros((shape[0],))], axis=0)
```

The first part (`mutils.to_flattened_numpy(data)`) is used to calculate the latent, while the second part (`np.zeros((shape[0],))`) is used to calculate the integral form.

**Comment by daihuiao** [comment]
I recently tried to train using only the calculated exact likelihood by first generating a two-dimensional Gaussian multimodal distribution data set (which was treated with clip) and then noising the data in that data set as described above. And calculate the final exact likelihood (tried both using hutchinsion's divergence calculation and the exact calculation method), the resulting data distribution looks like this:
![samples_original](https://github.com/user-attachments/assets/cf2bb4f2-1855-4950-ba5a-8112fb327567)
This is the original data distribution

![samples_4000](https://github.com/user-attachments/assets/da86b980-dc4c-4383-95a6-0e7654419af5)

This is a model trained using the likelihood method. As you can see, the model tends to output the average of all the data. Using the normal diffusion model loss can reproduce the data distribution here.  I guess this is because the training process does not add noise (because it is regarded as the ODE), and the process does not restrict the entire distribution migration process, that is, the data distribution at time T may not be Gaussian.
So somebody knows how to use likelihood methods to train diffusion models. Thank you.
